import {
  siteOrigin,
  basePath,
  siteUrl,
  businessName,
  email,
  phone,
  whatsappNumber,
  whatsappUrl,
  defaultTitle,
  defaultDescription,
  defaultOgImage,
  locale,
  author,
} from '../site.config.mjs';

export const site = {
  name: businessName,
  businessName,
  siteOrigin,
  domain: siteOrigin,
  basePath,
  siteUrl,
  description: defaultDescription,
  email,
  phone,
  whatsappNumber,
  whatsappUrl,
  contact: {
    email,
    phone,
    whatsapp: whatsappUrl,
  },
  defaultTitle,
  defaultDescription,
  defaultOgImage,
  locale,
  author,
};
