export const site = {
  name: 'Starts Digital',
  businessName: 'Starts Digital',
  siteUrl: 'https://firdosi.github.io/startsdigital',
  domain: 'https://firdosi.github.io',
  basePath: '/startsdigital',
  description: 'Digital marketing, paid advertising, websites, SEO, creative content and AI-powered marketing systems.',
  email: 'firdosidigital@gmail.com',
  phone: '+92 339 4135544',
  whatsappNumber: '+923394135544',
  whatsappUrl: 'https://wa.me/923394135544',
  contact: {
    email: 'firdosidigital@gmail.com',
    phone: '+92 339 4135544',
    whatsapp: 'https://wa.me/923394135544',
  },
  defaultTitle: 'Starts Digital | Digital Marketing Built to Scale Real Businesses',
  defaultDescription: 'Starts Digital helps businesses grow through paid advertising, high-converting websites, technical SEO, creative content, and practical AI-powered marketing systems.',
  defaultOgImage: '/og/default-og.png',
  locale: 'en_US',
  author: 'Starts Digital',
};
